CREATE TABLE TEST_TABLE (
  id                INTEGER NOT NULL,
  description       VARCHAR(100) NOT NULL COLLATE WIN_PTBR,
  created_date      DATE DEFAULT CURRENT_DATE NOT NULL,
  monetary_value    NUMERIC(15, 2) NOT NULL,
  blob_bin          BLOB SUB_TYPE 0 SEGMENT SIZE 80,
  blob_text         BLOB SUB_TYPE TEXT CHARACTER SET WIN1252,
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  bytes             SMALLINT
);
--;
ALTER TABLE TEST_TABLE ADD CONSTRAINT PK_TEST_TABLE PRIMARY KEY (id);
--;
GRANT ALL ON TEST_TABLE TO SYSADM WITH GRANT OPTION;
--;
CREATE SEQUENCE GEN_TEST_TABLE_ID;
--;
CREATE PROCEDURE SP_GEN_TEST_TABLE_ID
RETURNS (ID INTEGER)
AS
BEGIN
  ID = GEN_ID(GEN_TEST_TABLE_ID, 1);
  SUSPEND;
END;
--;
GRANT EXECUTE ON PROCEDURE SP_GEN_TEST_TABLE_ID TO SYSADM;
--;
INSERT INTO TEST_TABLE (id, description, monetary_value, bytes)
VALUES (NEXT VALUE FOR GEN_TEST_TABLE_ID, 'test 1', 1500.50, 255);
